Repository ansidev/awesome-nuxt, pull requests merged in 2023-05, with the labels that each got.

#136 Website vue-ecom.vercel.app
  content/resources/open-source-projects-using-nuxt.md
Labels: showcase

#139 Release v2.0.5
  .changes/v2.0.5.md
  CHANGELOG.md
  content/resources/modules.md
  package.json
  pnpm-lock.yaml
Labels: automated-pr, release-pr

#140 Merge branch 'release/2.0.5' into develop
  .changes/v2.0.5.md
  CHANGELOG.md
  package.json
Labels: automated-pr
